<a href="https://colab.research.google.com/github/Mahdi-Golizadeh/MODEL-COMPRESSION/blob/main/linear_quantization/quantizeAndDequantize_linearly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

this notebook is just a simple implementation of linear quantization. just to get a sense of the proess

In [1]:
import torch

to have linear quantization with zero point and arbitrary scale

In [2]:
def linear_quantization(tensor, scale, zero_point, dtype= torch.int8):
  # we first need to scale and zero center the input tensor
  scaled_shifted_tensor = tensor / scale + zero_point
  #now round the output of previous step
  round_tensor = torch.round(scaled_shifted_tensor)
  #calculate the max and min of the dtype
  q_min = torch.iinfo(dtype).min
  q_max = torch.iinfo(dtype).max
  q_tensor = round_tensor.clamp(q_min, q_max).to(dtype)
  return q_tensor

now to test the linear quantization funtion

In [4]:
input_tensor = torch.randn((3, 3)) * 100

initiate the zero point and scale randomly

In [5]:
scale = 3.5
zero_point = -70

In [6]:
quantized_tensor = linear_quantization(
    input_tensor,
    scale,
    zero_point,
)
quantized_tensor

tensor([[ -42,  -50,  -66],
        [ -87,  -77,  -72],
        [-114,  -92,  -75]], dtype=torch.int8)

now the dequantize process

In [7]:
def linear_dequantization(quantized_tensor, zero_point):
  return scale * (quantized_tensor.float() - zero_point)

In [9]:
dequantized_tensor = linear_dequantization(
    quantized_tensor,
    zero_point
)
dequantized_tensor

tensor([[  98.0000,   70.0000,   14.0000],
        [ -59.5000,  -24.5000,   -7.0000],
        [-154.0000,  -77.0000,  -17.5000]])

In [10]:
dequantized_tensor, input_tensor

(tensor([[  98.0000,   70.0000,   14.0000],
         [ -59.5000,  -24.5000,   -7.0000],
         [-154.0000,  -77.0000,  -17.5000]]),
 tensor([[  97.3035,   71.4544,   14.5617],
         [ -59.4350,  -23.8862,   -8.2211],
         [-152.5610,  -76.4821,  -16.8555]]))